### PR TITLE
[WIP] Added script for rebuilding freesolv

### PR DESCRIPTION
**Pull request by kyleabeauchamp**
@pgrinaway  this should do the trick for the GBFF stuff by dumping out a `gaff_mol2` directory containing `frcmod`, `mol2`, `prmtop`, and `inpcrd` files.

### CODE REVIEW

**Comment by pgrinaway** [comment]
Awesomeness, thanks!

**Comment by jchodera** [comment]
Can we put the FreeSolv rebuilding script in the FreeSolv/scripts directory
of the FreeSolv repo?

**Comment by kyleabeauchamp** [comment]
I'm hesitant to move things there until things have stabilized on our end, as the FreeSolve repo is much more public facing.

**Comment by jchodera** [comment]
To get around this, I've been to writing scripts for FreeSolv that are
standalone and can be refactored when we can use a stable public API from
something like gaff2xml.  Perhaps this is the best solution for now?

I feel that it is essential that any code that generated files in FreeSolv
must go into FreeSolv, or else we lose provenance information.

**Comment by kyleabeauchamp** [comment]
At this point, we have not generated any files for Freesolv.  When we do, we will put the code there.  This is a temporary solution so that we can make progress towards completing the GBFF project.

I do not want to hold up our GBFF work to make a public release of FreeSolv.

**Comment by jchodera** [comment]
> At this point, we have not generated any files for Freesolv. When we do, we will put the code there. This is a temporary solution so that we can make progress towards completing the GBFF project.
> I do not want to hold up our GBFF work to make a public release of FreeSolv.

Ah, OK.  That's fine, then, but essentially the same thing I was doing before (by putting the custom code in GBFF instead).

**Comment by kyleabeauchamp** [comment]
OK, I think the above comments and discussion with patrick suggests that this code belongs with GBFF for now.  I have filed a PR there.  

I am merging the minor API additions that remain in the present PR.

**Pull request merged**
