### PR TITLE
Added test of common molecules to illustrate failures

### PR DESCRIPTION
**Pull request by jchodera**
This builds in a test of `catechol` and `aspirin` and some other common molecules.
The test currently fails.  Debugging now...

### CODE REVIEW

**Comment by jchodera** [comment]
Note that travis tests pass because they skip the oechem-dependent tests.  The tests still fail on my machine.

**Comment by jchodera** [comment]
I think I see the problem.  The `utils.molecule_to_mol2()` method tries to name the files after their IUPAC names, but if this contains spaces, some of the toolchain fails:
```
IOError: [Errno 2] No such file or directory: '2-acetoxybenzoic acid.gaff.mol2'
-------------------- >> begin captured logging << --------------------
gaff2xml.openeye: DEBUG: 2-acetoxybenzoic acid
gaff2xml.utils: DEBUG: antechamber -i 2-acetoxybenzoic acid.tripos.mol2 -fi mol2 -o 2-acetoxybenzoic acid.gaff.mol2 -fo mol2 -s 2 -c bcc
gaff2xml.utils: DEBUG: Flag not recognized: acid.tripos.mol2
Use antechamber -h for command-line syntax
gaff2xml.utils: DEBUG: parmchk2 -i 2-acetoxybenzoic acid.gaff.mol2 -f mol2 -o 2-acetoxybenzoic acid.frcmod
gaff2xml.utils: DEBUG: Error: invalid input file format(valid: prepi, prepc, ac, mol2)!
--------------------- >> end captured logging << ---------------------
```
Would be good to ensure everything handles spaces correctly.

**Comment by kyleabeauchamp** [comment]
+1 to merge.  

Just one failure on my machine, possibly the same spaces in names issue as mentioned previously.

```
kyleb@kyleb-DX4870:~$ nosetests gaff2xml -v -a '!slow'
Testing molecule benzene ... ok
Testing molecule toluene ... ok
Testing molecule phenol ... ok
Testing molecule benzene-1,2-diol ... ok
Testing molecule 2-acetoxybenzoic acid ... ok
Failure: AttributeError ('OEGraphMol' object has no attribute 'GetConfs') ... ERROR
test_drugs_no_oechem.test_drugs_fast ... ok


======================================================================
ERROR: Failure: AttributeError ('OEGraphMol' object has no attribute 'GetConfs')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/kyleb/opt/lib/python2.7/site-packages/nose/loader.py", line 251, in generate
    for test in g():
  File "/home/kyleb/opt/lib/python2.7/site-packages/gaff2xml-0.1-py2.7.egg/gaff2xml/tests/test_drugs.py", line 38, in test_drug
    molecule_name, tripos_mol2_filename = utils.molecule_to_mol2(molecule)
  File "/home/kyleb/opt/lib/python2.7/site-packages/gaff2xml-0.1-py2.7.egg/gaff2xml/utils.py", line 418, in molecule_to_mol2
    return gaff2xml.openeye.molecule_to_mol2(*args, **kwargs)
  File "/home/kyleb/opt/lib/python2.7/site-packages/gaff2xml-0.1-py2.7.egg/gaff2xml/openeye.py", line 253, in molecule_to_mol2
    for k, mol in enumerate(molecule.GetConfs()):
AttributeError: 'OEGraphMol' object has no attribute 'GetConfs'
-------------------- >> begin captured logging << --------------------
gaff2xml.openeye: DEBUG: ZINC03873936
--------------------- >> end captured logging << ---------------------

----------------------------------------------------------------------
```

**Comment by jchodera** [comment]
Looks like you have an unrelated issue, possibly due to an outdated OEChem version?
```
AttributeError: 'OEGraphMol' object has no attribute 'GetConfs'
```
It's odd that the spaces issue doesn't appear on your system but *does* appear on `osx`.

Is there a way to make sure we use OS-generated temporary files and directories for intermediate files?  This seems like it would be more robust than using molecule names that may be problematic.

**Comment by kyleabeauchamp** [comment]
Yeah, I think that sounds like a reasonable plan.

**Pull request merged**
