### PR TITLE
Raise exception if assign charges fails

### PR DESCRIPTION
**Pull request by kyleabeauchamp**

### CODE REVIEW

**Comment by jchodera** [comment]
Awesome, thanks! 

Do you want a test molecule that fails this?

**Comment by kyleabeauchamp** [comment]
Do you have one offhand?  I tried rapamycin and paclitaxel, but they seemed to work fine.

**Comment by bas-rustenburg** [comment]
Try something unphysical?

**Comment by jchodera** [comment]
Yes, I have a bunch.

Here's one:
https://gist.github.com/jchodera/7833b895fd66d6ff5411

**Comment by kyleabeauchamp** [comment]
OK, this was a bit more subtle than I had thought, as charging can go wrong during both Omega and AssignPartialCharges.  I'm now checking both statuses and raising exceptions.

**Pull request merged**
